###############################################################################
# Cloud SQL (Postgres 15) with the pgvector extension installed.
#
# The lifecycle agent retrieves playbook chunks from the `playbook_chunks`
# table — schema is created by `rag/store.py::init_schema()` on first run, not
# here, so the SQL stays in the application layer where it's tested.
#
# The root password is generated by Terraform and stored in Secret Manager.
# Cloud Run services read it via the `secret_manager` module (later phases).
###############################################################################

resource "random_password" "root" {
  length  = 32
  special = true
}

resource "google_sql_database_instance" "pgvector" {
  name                = var.instance_name
  project             = var.project_id
  region              = var.region
  database_version    = "POSTGRES_15"
  deletion_protection = var.deletion_protection

  settings {
    tier = var.tier

    # pgvector ships with Cloud SQL Postgres 15; we only need to flip the flag
    # to make the extension installable by the application.
    database_flags {
      name  = "cloudsql.enable_pgvector"
      value = "on"
    }

    backup_configuration {
      enabled                        = true
      point_in_time_recovery_enabled = true
      start_time                     = "03:00"
    }

    ip_configuration {
      ipv4_enabled = true
      # Production should add `private_network` + Cloud SQL Auth Proxy. For
      # the demo we leave a public IP so `terraform apply` works out of the box;
      # authorized networks is an empty list so nothing can actually connect.
      authorized_networks {
        name  = "intentionally-empty"
        value = "127.0.0.1/32"
      }
    }

    user_labels = var.labels
  }
}

resource "google_sql_database" "db" {
  project  = var.project_id
  name     = var.database_name
  instance = google_sql_database_instance.pgvector.name
}

resource "google_sql_user" "root" {
  project  = var.project_id
  name     = "grafanagent"
  instance = google_sql_database_instance.pgvector.name
  password = random_password.root.result
}

resource "google_secret_manager_secret" "pgvector_dsn" {
  project   = var.project_id
  secret_id = "${var.instance_name}-dsn"

  replication {
    auto {}
  }

  labels = var.labels
}

resource "google_secret_manager_secret_version" "pgvector_dsn" {
  secret = google_secret_manager_secret.pgvector_dsn.id
  secret_data = format(
    "postgresql://%s:%s@%s/%s",
    google_sql_user.root.name,
    random_password.root.result,
    google_sql_database_instance.pgvector.public_ip_address,
    google_sql_database.db.name,
  )
}
